name: kawshik
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # GitHub
  github: ^9.2.0

  # Web related
  flutter_html: any
  url_strategy: ^0.2.0
  universal_html: ^2.0.4

  # HTTP
  http: ^1.2.1

  # Utils
  mailto: ^2.0.0
  flip_card: ^0.7.0
  url_launcher: ^6.2.6
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  animated_text_kit: ^4.2.2
  font_awesome_flutter: ^10.1.0

  # State management
  provider: ^6.0.1

  # Cache
  shared_preferences: ^2.0.6
  image_gallery_saver: ^2.0.3
  share: ^2.0.4
  mailer: ^6.1.0
  path_provider: ^2.0.2
  math_expressions: ^2.0.0
  flutter_svg: ^2.0.9
  weather_icons: ^3.0.0
  geolocator: ^12.0.0
  folio:
    path: U:\pvlab\Portfolio-with-Flutter-main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
